### ISSUE TITLE
生成代码时，报错：Cause: java.sql.SQLException: Field 'table_id' doesn't have a default value，疑似mybatis-plus插入数据后，未返回主键

### ISSUE THREAD

**Issue by lymansix** [YunaiV/yudao-cloud#68]
### 基本信息

- yudao-cloud：
- 操作系统：win10 ltsc 2021 64bit
- 数据库：mysql 8.0

### 你猜测可能的原因
插入数据后未返回table.id 
`codegenTableMapper.insert(table);`
导致下一步table.id无值可用
```java
       // 构建 CodegenColumnDO 数组，插入到 DB 中
        List<CodegenColumnDO> columns = codegenBuilder.buildColumns(table.getId(), tableInfo.getFields());
        // 如果没有主键，则使用第一个字段作为主键
        if (!tableInfo.isHavePrimaryKey()) {
            columns.get(0).setPrimaryKey(true);
        }
        codegenColumnMapper.insertBatch(columns);
```

### 复现步骤

第一步，进入后台管理系统，选择左侧“基础设施”菜单

第二步，选择“代码生成”

第三步，点击“导入”按钮，选择表后确定

### 报错信息
系统异常
![图片](https://user-images.githubusercontent.com/6296190/186559943-541478a3-cfb6-4169-9a06-e67d83ee8b61.png)
### Cause: java.sql.SQLException: Field 'table_id' doesn't have a default value
; Field 'table_id' doesn't have a default value; nested exception is java.sql.SQLException: Field 'table_id' doesn't have a default value
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:251)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:91)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441)
	at com.sun.proxy.$Proxy205.insert(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:272)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:59)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:148)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89)
	at com.sun.proxy.$Proxy232.insert(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1259)

**Comment by lymansix** [comment]
经测试，将配置文件主键类型更改后，功能正常
```yaml
global-config:
    db-config:
      id-type: AUTO
```
